spring:
  jpa:
    hibernate:
      show_sql: true
      format_sql: true
      highlight_sql: true
      use_sql_comments: true
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/datajpa
    username: root
    password: 316201
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  api-docs:
    enabled: true
    path: /docs/json

  swagger-ui:
    enabled: true
    path: /docs
    display-request-duration: true

  cache:
    disabled: true


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE